added node js week1
pattnaikupasana/meal-sharing pull request #1
Opened 2023-06-12 18:38 UTC by pattnaikupasana

2023-06-12 20:16 UTC, itsgauravsaxena requested changes
Please consider comments as stated

2023-06-12 20:16 UTC, itsgauravsaxena commented on src/backend/app.js
> +      "SELECT * FROM meal WHERE `when` > NOW()"
Please try to use knex syntax instead of raw sql. Like knex.select()
Please refer to cheat sheet!

2023-06-12 20:16 UTC, itsgauravsaxena commented on src/backend/app.js
> +    console.log(futureMeals);
Always good idea to remove console log statements

2023-06-12 20:16 UTC, itsgauravsaxena commented on src/backend/app.js
> +    const pastMeals = await knex.raw("SELECT * FROM meal WHERE `when` < NOW()");
Same as above comments

2023-06-12 20:19 UTC, pattnaikupasana commented on src/backend/app.js
> +      "SELECT * FROM meal WHERE `when` > NOW()"
Ok will follow the syntax.

2023-06-15 18:31 UTC, pattnaikupasana commented
Thank you so much for the feedback 🙏

2023-06-15 18:31 UTC, merged